name: Deploy the Product Page to GitHub Pages

env: # Change these to your preferences any image url can also be a base encoded image
    GITHUB_PAGES_BRANCH: gh-pages

    # options: "true" | "false"
    USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: "true"
    
    GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
    API_BASE_URL: "https://api.gateway.commonground.nu/api"
    NL_DESIGN_THEME_CLASSNAME: "xxllnc-theme"
    FAVICON_URL: "https://xxllnc.nl/wp-content/uploads/2021/07/cropped-fav-xxllnc-32x32.png"
    HEADER_LOGO_URL: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI1LjIuMywgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCAxNzUuNCA0Mi4yIiBzdHlsZT0iZW5hYmxlLWJhY2tncm91bmQ6bmV3IDAgMCAxNzUuNCA0Mi4yOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxwYXRoIGQ9Ik03OC4zLDQwLjdoNy4yVjAuNGgtNy4yVjQwLjd6IE05NC44LDQwLjdoNy4yVjAuNGgtNy4yVjQwLjd6IE02NC41LDkuNEw1My40LDIwLjhsLTExLTExLjRsLTQuOCw0LjlsMTEuMSwxMS40TDM3LjYsMzcuMQoJbDQuOCw0LjlsMTEuMS0xMS40bDExLDExLjRsNC44LTQuOUw1OC4yLDI1LjdsMTEuMS0xMS40TDY0LjUsOS40eiBNMjcuMiw5LjRMMTYuMSwyMC44TDUuMSw5LjRsLTQuOCw0LjlsMTEuMSwxMS40TDAuMywzNy4xTDUuMSw0MgoJbDExLjEtMTEuNGwxMSwxMS40bDQuOC00LjlMMjAuOSwyNS43TDMyLDE0LjNMMjcuMiw5LjR6IE0xMjQuOCwxMC43Yy04LjIsMC0xNC4zLDUuMi0xNC4zLDE0LjF2MTUuOWg3LjJWMjVjMC00LjgsMy03LjMsNy4xLTcuMwoJczcuMSwyLjYsNy4xLDcuM3YxNS44aDcuMnYtMTZDMTM5LjEsMTUuOCwxMzMsMTAuNywxMjQuOCwxMC43eiBNMTYwLjQsMzQuOGMtNC41LDAtOC4yLTMuOS04LjItOC44YzAtNC44LDMuNy04LjgsOC4yLTguOAoJYzMuNCwwLDYuMywyLjIsNy41LDUuM2g3LjJjLTEuMy03LTcuMS0xMS44LTE0LjYtMTEuOGMtOC44LDAtMTUuMiw2LjUtMTUuMiwxNS40YzAsOC44LDYuNCwxNS4zLDE1LjIsMTUuMwoJYzcuNSwwLDEzLjMtNC44LDE0LjYtMTEuN2gtNy4yQzE2Ni42LDMyLjYsMTYzLjcsMzQuOCwxNjAuNCwzNC44eiIvPgo8L3N2Zz4K"
    ORGANISATION_NAME: "xxllnc"
    JUMBOTRON_IMAGE_URL: "https://uploads.magnetme-images.com/bf3b2064d7a7c8a51b2c66608b62160f01ee478ab2df8a493635c92069405d35?auto=compress&auto=format&fit=crop&frame=0&h=1125&w=2000"
    FOOTER_LOGO_URL: "https://xxllnc.nl/wp-content/uploads/2021/04/xxllnc-kleur.svg"
    FOOTER_LOGO_HREF: "https://xxllnc.nl/"
    FOOTER_CONTENT: '[{"title":"Algemeen","items":[{"label":"Website","value":"www.xxllnc.nl","link":"https://xxllnc.nl/"},{"label":"Contact","value":"Neem contact op","link":"https://xxllnc.nl/contact"}]}]'
    OIDN_NUMBER: " "

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Get the WOO Website Template Code
              uses: actions/checkout@v2
              with:
                  repository: ConductionNL/woo-website-template
                  ref: development

            # With special thanxs to https://github.com/SpicyPizza/create-envfile
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_GITHUB_REPOSITORY_NAME: ${{ env.GITHUB_REPOSITORY_NAME }}
                  envkey_USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX: ${{ env.USE_GITHUB_REPOSITORY_NAME_AS_PATH_PREFIX }}
                  envkey_GATSBY_API_BASE_URL: ${{ env.API_BASE_URL }}
                  envkey_GATSBY_NL_DESIGN_THEME_CLASSNAME: ${{ env.NL_DESIGN_THEME_CLASSNAME }}
                  envkey_GATSBY_FAVICON_URL: ${{ env.FAVICON_URL }}
                  envkey_GATSBY_HEADER_LOGO_URL: ${{ env.HEADER_LOGO_URL }}
                  envkey_GATSBY_ORGANISATION_NAME: ${{ env.ORGANISATION_NAME }}
                  envkey_GATSBY_JUMBOTRON_IMAGE_URL: ${{ env.JUMBOTRON_IMAGE_URL }}
                  envkey_GATSBY_FOOTER_LOGO_URL: ${{ env.FOOTER_LOGO_URL }}
                  envkey_GATSBY_FOOTER_LOGO_HREF: ${{ env.FOOTER_LOGO_HREF }}
                  envkey_GATSBY_FOOTER_CONTENT: ${{ env.FOOTER_CONTENT }}
                  envkey_GATSBY_OIDN_NUMBER: ${{ env.OIDN_NUMBER }}
                  directory: pwa/static
                  file_name: .env.production
                  fail_on_empty: true
                  sort_keys: false

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install dependencies
              run: cd pwa && npm install

            - name: Remove old Gatsby cache
              run: rm -rf pwa/.cache

            - name: Build application
              run: cd pwa && npm run build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.0
              with:
                  branch: ${{ env.GITHUB_PAGES_BRANCH }}
                  folder: pwa/public
